import type { Imovel } from "./types";

import img01 from "@/assets/imovel-01.jpg";
import img02 from "@/assets/imovel-02.jpg";
import img03 from "@/assets/imovel-03.jpg";
import img04 from "@/assets/imovel-04.jpg";

/**
 * Acervo DEMONSTRATIVO. Nenhum dado real: todos os imóveis estão marcados
 * como exemplo e a origem é explícita na apresentação.
 */
export const IMOVEIS: Imovel[] = [
  {
    id: "imv-001",
    titulo: "Frente-mar com três suítes e vista aberta",
    cidade: "Balneário Camboriú",
    bairro: "Centro",
    tipo: "apartamento",
    frenteMar: true,
    quadraMar: false,
    suites: 3,
    vagas: 3,
    areaPrivativa: 186,
    status: "pronto",
    preco: 4_850_000,
    capa: img01,
    galeria: [img01, img03, img04, img02],
    descricao:
      "Andar alto voltado para a orla, com living integrado à varanda e vista contínua da praia. Pronto para morar, sem obras pendentes.",
    caracteristicas: ["Living integrado", "Varanda com churrasqueira", "Andar alto", "Mobiliado"],
    origem: { tipo: "demonstracao", nome: "Imóvel de demonstração" },
    confianca: { preco: "informado", area: "informado", frenteMar: "confirmado", entrega: "confirmado" },
    referenciaLocalizacao: "Avenida Atlântica, quadra da orla",
    distanciaMar: "Frente para a praia",
  },
  {
    id: "imv-002",
    titulo: "Frente-mar, três suítes, acima do orçamento",
    cidade: "Balneário Camboriú",
    bairro: "Barra Sul",
    tipo: "apartamento",
    frenteMar: true,
    quadraMar: false,
    suites: 3,
    vagas: 2,
    areaPrivativa: 214,
    status: "pronto",
    preco: 5_300_000,
    capa: img03,
    galeria: [img03, img01, img04],
    descricao:
      "Planta ampla com três suítes e living de frente para o mar. Metragem maior que a média da região, o que explica o valor.",
    caracteristicas: ["Planta ampla", "Duas vagas", "Lazer completo"],
    origem: { tipo: "demonstracao", nome: "Imóvel de demonstração" },
    confianca: { preco: "informado", area: "estimado", frenteMar: "confirmado", entrega: "confirmado" },
    referenciaLocalizacao: "Barra Sul, próximo à passarela",
    distanciaMar: "Frente para a praia",
  },
  {
    id: "imv-003",
    titulo: "Quadra-mar pronto, três suítes",
    cidade: "Balneário Camboriú",
    bairro: "Centro",
    tipo: "apartamento",
    frenteMar: false,
    quadraMar: true,
    suites: 3,
    vagas: 3,
    areaPrivativa: 172,
    status: "pronto",
    preco: 4_150_000,
    capa: img04,
    galeria: [img04, img03, img02],
    descricao:
      "Primeira quadra da praia, com vista lateral do mar. Não é frente-mar, mas mantém a caminhada curta até a areia.",
    caracteristicas: ["Vista lateral do mar", "Três vagas", "Pronto para morar"],
    origem: { tipo: "demonstracao", nome: "Imóvel de demonstração" },
    confianca: { preco: "informado", area: "informado", frenteMar: "confirmado", entrega: "confirmado" },
    referenciaLocalizacao: "Primeira quadra, a 120 m da areia",
    distanciaMar: "Cerca de 120 m do mar",
  },
  {
    id: "imv-004",
    titulo: "Frente-mar em construção, quatro suítes",
    cidade: "Balneário Camboriú",
    bairro: "Barra Norte",
    tipo: "apartamento",
    frenteMar: true,
    quadraMar: false,
    suites: 4,
    vagas: 4,
    areaPrivativa: 258,
    status: "construcao",
    preco: 6_900_000,
    capa: img02,
    galeria: [img02, img01, img03],
    descricao:
      "Lançamento frente-mar com quatro suítes e entrega prevista para os próximos anos. Ainda não é pronto para morar.",
    caracteristicas: ["Lançamento", "Quatro suítes", "Vista permanente"],
    origem: { tipo: "demonstracao", nome: "Imóvel de demonstração" },
    confianca: { preco: "informado", area: "informado", frenteMar: "informado", entrega: "estimado" },
    referenciaLocalizacao: "Barra Norte, orla",
    distanciaMar: "Frente para a praia",
  },
  {
    id: "imv-005",
    titulo: "Frente-mar compacto, duas suítes",
    cidade: "Balneário Camboriú",
    bairro: "Pioneiros",
    tipo: "apartamento",
    frenteMar: true,
    quadraMar: false,
    suites: 2,
    vagas: 2,
    areaPrivativa: 118,
    status: "pronto",
    preco: 3_450_000,
    capa: img01,
    galeria: [img01, img04],
    descricao:
      "Metragem enxuta com o mar na frente. Duas suítes, ideal para quem prioriza a vista sobre o tamanho.",
    caracteristicas: ["Vista frontal do mar", "Reformado", "Pronto para morar"],
    origem: { tipo: "demonstracao", nome: "Imóvel de demonstração" },
    confianca: { preco: "informado", area: "informado", frenteMar: "confirmado", entrega: "confirmado" },
    referenciaLocalizacao: "Pioneiros, orla",
    distanciaMar: "Frente para a praia",
  },
  {
    id: "imv-006",
    titulo: "Frente-mar em Itapema, três suítes",
    cidade: "Itapema",
    bairro: "Meia Praia",
    tipo: "apartamento",
    frenteMar: true,
    quadraMar: false,
    suites: 3,
    vagas: 2,
    areaPrivativa: 164,
    status: "pronto",
    preco: 4_300_000,
    capa: img03,
    galeria: [img03, img04, img02],
    descricao:
      "Meia Praia, frente-mar, três suítes e praia mais tranquila. Outra cidade, mesmo perfil de imóvel.",
    caracteristicas: ["Praia tranquila", "Frente-mar", "Pronto para morar"],
    origem: { tipo: "demonstracao", nome: "Imóvel de demonstração" },
    confianca: { preco: "informado", area: "estimado", frenteMar: "confirmado", entrega: "confirmado" },
    referenciaLocalizacao: "Meia Praia, orla",
    distanciaMar: "Frente para a praia",
  },
];

export function buscarImovel(id: string) {
  return IMOVEIS.find((i) => i.id === id);
}
